name: flutter_application_1
description: A new Flutter project.


publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.6
  flutter_spinkit: ^5.1.0
  flutter_barcode_scanner: ^2.0.0
  shared_preferences: ^2.0.5
  easy_localization: ^3.0.1
  http: ^0.13.5
  youtube_player_flutter: ^8.1.2
  fluttertoast: ^8.0.7
  firebase_core: ^2.15.0
  qr_flutter: ^4.0.0
  firebase_auth: ^4.7.0
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations :
    sdk: flutter   

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resource/langs/ar.json
    - resource/langs/en.json
    - assets/
    - assets/images/
    - assets/login.jpg
    - assets/onboarding_logo1.svg
    - assets/onboarding_logo2.svg
    - assets/solid_circle_ic.svg
    - assets/left_arrow_ic.svg
    - assets/right_arrow_ic.svg
    - assets/profile.svg
   

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
